server:
  port: 8000

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: answer-service
#          uri: http://localhost:8080 # 포워딩할 주소, http://localhost:8000/answer 로 들어오면 http://localhost:64412 로 포워딩
          uri: lb://ANSWER-SERVICE
          predicates:
            - Path=/answer/** # 해당 gateway 서버의 /user/**로 들어오는 요은 user-service로 인식하겠다는 조건
          filters:
            - RewritePath=/answer/?(?<segment>.*), /$\{segment}

        - id: survey-service
#          uri: http://localhost:8081 # 포워딩할 주소, http://localhost:8000/answer 로 들어오면 http://localhost:64412 로 포워딩
          uri: lb://SURVEY-SERVICE
          predicates:
            - Path=/survey/** # 해당 gateway 서버의 /user/**로 들어오는 요은 user-service로 인식하겠다는 조건
          filters:
            - RewritePath=/survey/?(?<segment>.*), /$\{segment}

        - id: user-service
            #          uri: http://localhost:8081 # 포워딩할 주소, http://localhost:8000/answer 로 들어오면 http://localhost:64412 로 포워딩
#          uri: http://210.109.60.38:8082
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/** # 해당 gateway 서버의 /user/**로 들어오는 요은 user-service로 인식하겠다는 조건
          filters:
            - RewritePath=/user/?(?<segment>.*), /$\{segment}

        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-doc


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone : http://admin:admin@${eureka.instance.hostname}:8761/eureka/
  instance:
    hostname: 172.16.4.35

springdoc:
  swagger-ui:
    urls:
      - name: user
        url: /v3/api-docs/user
      - name: survey
        url: /v3/api-docs/survey
      - name: answer
        url: /v3/api-docs/answer