server:
  port: 8000

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: answer-service
#          uri: http://localhost:8080 # 포워딩할 주소, http://localhost:8000/answer 로 들어오면 http://localhost:64412 로 포워딩
          uri: lb://ANSWER-SERVICE
          predicates:
            - Path=/answer/** # 해당 gateway 서버의 /user/**로 들어오는 요은 user-service로 인식하겠다는 조건
          filters:
            - RewritePath=/answer/?(?<segment>.*), /$\{segment}

        - id: survey-service
#          uri: http://localhost:8081 # 포워딩할 주소, http://localhost:8000/answer 로 들어오면 http://localhost:64412 로 포워딩
          uri: lb://SURVEY-SERVICE
          predicates:
            - Path=/survey/** # 해당 gateway 서버의 /user/**로 들어오는 요은 user-service로 인식하겠다는 조건
          filters:
            - RewritePath=/survey/?(?<segment>.*), /$\{segment}

        - id: user-service
            #          uri: http://localhost:8081 # 포워딩할 주소, http://localhost:8000/answer 로 들어오면 http://localhost:64412 로 포워딩
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/** # 해당 gateway 서버의 /user/**로 들어오는 요은 user-service로 인식하겠다는 조건
          filters:
            - RewritePath=/survey/?(?<segment>.*), /$\{segment}


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone : http://admin:admin@localhost:8761/eureka/
  instance:
    hostname: localhost
