server:
  port: 8888

spring:
  application:
    name: config-service

  cloud:
    config:
      server:
        git:
          uri: https://github.com/GC-HeyKakao/HeyForm-Config.git
          username: parkchanbin54
          password: 
          default-label: main
          ignore-local-ssh-settings: true

#management:
#  endpoints:
#    web:
#      exposure:
#        include: busrefresh
